version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.7.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
