docker_builder:
  env:
    CONTAINER: "deber-xyz-abc"
    DEBER_LINTIAN_FLAGS: "-i -I --allow-root"
    DEBER_DPKG_BUILDPACKAGE_FLAGS: "-tc"
  script:
    - docker create --name $CONTAINER -t -v "$PWD":"/build" -w "/build" golang:1.11.4 sleep inf
    - docker start $CONTAINER
    - docker exec -t $CONTAINER go build
    - docker exec -t $CONTAINER go test -v -count 3 ./...
    - test -z $(docker exec -t $CONTAINER gofmt -l .)
    - mv deber /usr/bin/
    - deber --version
    - deber --list
    - deber --exclude remove,stop
    - deber --remove