docker_builder:
  env:
    CONTAINER: "deber-xyz-abc"
  create_script:
    - docker create --name $CONTAINER -t -v "$PWD":"/build" -w "/build" golang:1.11.4 sleep inf
  start_script:
    - docker start $CONTAINER
  build_script:
    - docker exec -t $CONTAINER go build -mod=vendor
  test_script:
    - docker exec -t $CONTAINER go test -mod=vendor -v -count 3 ./...
  fmt_script:
    - test -z $(docker exec -t $CONTAINER gofmt -l pkg main.go)
  install_script:
    - mv deber /usr/bin/
  deber_script:
    - deber --version
    - deber
