.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DEBER" "1" "March 2019" "" ""
.
.SH "NAME"
\fBdeber\fR \- Debian packaging with Docker
.
.SH "SYNOPSIS"
\fBdeber\fR [flags]
.
.SH "DESCRIPTION"
Utility made with simplicity in mind to provide an easy way for building Debian packages in Docker containers\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
help for deber
.
.TP
\fB\-\-dpkg\-buildpackage\-flags\fR \fIstring\fR
specify flags passed to dpkg\-buildpackage (default "\-tc")
.
.TP
\fB\-\-lintian\-flags\fR \fIstring\fR
specify flags passed to lintian (default "\-i")
.
.TP
\fB\-u\fR, \fB\-\-update\-after\fR \fIstring\fR
perform apt cache update after specified interval (default 30m0s)
.
.TP
\fB\-f\fR, \fB\-\-from\fR \fIstring\fR
specify which Docker image to use (default "debian:unstable")
.
.TP
\fB\-r\fR, \fB\-\-repo\fR \fIstring\fR
specify a local repository to be mounted in container
.
.TP
\fB\-c\fR, \fB\-\-clean\fR
stop and remove uncleaned container
.
.TP
\fB\-\-version\fR
version for deber
.
.SH "STEPS"
The following steps are executed (in that exact order):
.
.P
\fBbuild\fR
.
.IP "" 4
.
.nf

Build Docker image\. This step is skipped if an image is already built\.
.
.fi
.
.IP "" 0
.
.P
\fBcreate\fR
.
.IP "" 4
.
.nf

  Create Docker container\.
.
.fi
.
.IP "" 0
.
.P
\fBstart\fR
.
.IP "" 4
.
.nf

  Start Docker container\.
.
.fi
.
.IP "" 0
.
.P
\fBpackage\fR
.
.IP "" 4
.
.nf

  Run series of commands in Docker container:
   \- apt\-get update
   \- mk\-build\-deps
   \- dpkg\-buildpackage
.
.fi
.
.IP "" 0
.
.P
\fBtest\fR
.
.IP "" 4
.
.nf

  Run series of commands in Docker container:
   \- debc
   \- debi
   \- lintian
.
.fi
.
.IP "" 0
.
.P
\fBstop\fR
.
.IP "" 4
.
.nf

  Stop Docker container\.
.
.fi
.
.IP "" 0
.
.P
\fBremove\fR
.
.IP "" 4
.
.nf

  Remove Docker container\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
Using deber with gbp:
.
.IP "" 4
.
.nf

$ gbp buildpackage \-\-git\-builder deber
.
.fi
.
.IP "" 0
.
.P
Using deber (with flags) with gbp:
.
.IP "" 4
.
.nf

$ gbp buildpackage \-\-git\-builder deber \-\-from debian:buster
.
.fi
.
.IP "" 0
.
.P
Specifying different OS and Distribution:
.
.IP "" 4
.
.nf

$ deber \-\-from ubuntu:bionic
.
.fi
.
.IP "" 0
.
.P
Build package with custom dpkg\-buildpackage flags:
.
.IP "" 4
.
.nf

$ deber \-\-dpkg\-buildpackage\-flags "\-nc \-S"
.
.fi
.
.IP "" 0
.
.P
Test package with custom lintian flags:
.
.IP "" 4
.
.nf

$ deber \-\-lintian\-flags "\-i \-I"
.
.fi
.
.IP "" 0
.
.P
Mount local repo and use it in container:
.
.IP "" 4
.
.nf

$ deber \-\-repo $HOME/repo/unstable
.
.fi
.
.IP "" 0
.
.P
Update apt cache now:
.
.IP "" 4
.
.nf

$ deber \-\-update\-after 0
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
gbp(1), gbp\-buildpackage(1), lintian(1)
