name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: Build
        run: go build -v -o /tmp/deber
      - name: Test
        run: go test -v -count=3 ./...
      - name: Run
        run: /tmp/deber
