name: Tests

on: push

jobs:
  tests:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Build
        run: go build -v -mod=vendor -o /tmp/deber
      - name: Test
        run: go test -v -mod=vendor -count=3 ./...
      - name: Run
        run: /tmp/deber
